# -*- coding: utf-8 -*-
"""AbhayNetra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gb30PlJBSTjRzlKJccHNVisQKJFw_PG-

### **Reading Dataset and Performing EDA**
"""
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df = pd.read_csv('Traffic Data.csv')

print(df)

df.info()

"""### **Training The Model**"""

x=df[['Traffic_Density']]
y=df['Light']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.8, random_state=67)

model = LogisticRegression()
model.fit(x_train, y_train)

print(int(model.predict([[34]])))

with open('model.pkl', 'wb') as f:
  pickle.dump(model, f)

# """### **Testing The Model**"""

# y_pred = model.predict(x_test)

# for i in range(len(y_pred)):
#     print(y_pred[i], y_test.values[i])

# accuracy = accuracy_score(y_test, y_pred)
# print(accuracy)

# currDensity=[[int(input("Enter Current Traffic Density: "))]]
# if (model.predict(currDensity) == 1):
#   print("Light is Green")
# else:
#   print("Light is Red")
